language: php
sudo: required
services:
  - docker
php:
  - 5.6
  - 7.0
before_install:
  - git submodule update --init --recursive
  - .travis/install-docker-compose.sh
install:
  - composer install
  - cp phpunit.xml.dist phpunit.xml
  - docker-compose -f .travis/docker-compose.yml up -d && .travis/wait-for-it.sh -h localhost -p 5171 -t 30
script:
  - ./vendor/bin/phpunit
