language: php
sudo: required
services:
  - docker
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
before_install:
  - git submodule update --init --recursive
install:
  - composer install
  - cp phpunit.xml.dist phpunit.xml
  - docker-compose up -f .travis/docker-compose.yml -d
script:
  - ./vendor/bin/phpunit
